
DEBUG_TOOLBAR_MIDDLEWARE_CLASSES = ('debug_toolbar.middleware.DebugToolbarMiddleware',) # DEBUG
DEBUG_TOOLBAR_INSTALLED_APPS = ('debug_toolbar',) #DEBUG

DEBUG_TOOLBAR_INTERNAL_IPS = ('127.0.0.1',) # DEBUG
DEBUG_TOOLBAR_DEBUG_TOOLBAR_CONFIG = {"INTERCEPT_REDIRECTS": False} # DEBUG
